// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO97Xa5OSQDkLeuUs_GK0Skm_-xWu0FkY',
    appId: '1:347072479376:web:673694f185e51339909815',
    messagingSenderId: '347072479376',
    projectId: 'qrpres',
    authDomain: 'qrpres.firebaseapp.com',
    storageBucket: 'qrpres.appspot.com',
    measurementId: 'G-F5RMKZBNDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcRQvwy8ysSaoACCENJbhFnEArm0TwHgs',
    appId: '1:347072479376:android:34a7707797d90060909815',
    messagingSenderId: '347072479376',
    projectId: 'qrpres',
    storageBucket: 'qrpres.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA83Fovf2nBO2UkoBmJ1kCtWa9nGvvUN6Y',
    appId: '1:347072479376:ios:7d19a5bb039ebc67909815',
    messagingSenderId: '347072479376',
    projectId: 'qrpres',
    storageBucket: 'qrpres.appspot.com',
    iosClientId: '347072479376-oq2pe7d90l3erkqugulp5vj7esvle58l.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrPres',
  );
}
